# -*- coding: utf-8 -*-
"""a5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9M8Lvwhsf4MHL3dNcwSCMCasSPSfYmh
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

life_df = pd.read_csv('/content/Life_Expectancy_Data.csv')
life_df.fillna(0, inplace=True)
life_df.head(3)

sns.violinplot(data=life_df, y='Polio', inner='quart').set_title('% Polio inoculation Coverage')

sns.violinplot(data=life_df, y='Diphtheria ', inner='quart').set_title('% Diphtheria inoculation Coverage')

heat_df = life_df.drop(['Country', 'Year', 'Status'], axis=1)
corr = heat_df.corr()
sns.heatmap(corr, cmap='RdBu')

life_df.sort_values(by=['Life expectancy ']).head(10)

life_df.sort_values(by='Life expectancy ', ascending = False).head(10)

heat_df.describe()